# Default values for spring-nacos-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
hub: build-harbor.alauda.cn
ns:
  client: spring-nacos-demo-client
  workload: spring-nacos-demo
image:
  consumer:
    repository: test/asm
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "changename"
    dashboardTag: "latest"
  provider:
    repository: test/asm
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "changename"

nacos:
  server: nacos-cs.default:8848
  user: nacos
  password: nacos

service:
  consumer:
    type: ClusterIP
    port: 18083
  provider:
    type: ClusterIP
    port: 18082

env:
  namespace: public
  group: DEFAULT_GROUP
  cluster: DEFAULT
  oa:
    namespace: 62698514-6731-4d7f-a61f-fce4e929431b
    dev:
      prefix: -oa-dev
      group: dev
      cluster: DEFAULT
    qa:
      prefix: -oa-qa
      group: qa
      cluster: DEFAULT
  crm:
    namespace: 3017e721-0326-4360-8f3a-17471f5ca08f
    dev:
      prefix: -crm-dev
      group: dev
      cluster: DEFAULT
    qa:
      prefix: -crm-qa
      group: qa
      cluster: DEFAULT

#
#imagePullSecrets: []
#nameOverride: ""
#fullnameOverride: ""
#
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
#
#podAnnotations: {}
#
#podSecurityContext: {}
#  # fsGroup: 2000
#
#securityContext: {}
#  # capabilities:
#  #   drop:
#  #   - ALL
#  # readOnlyRootFilesystem: true
#  # runAsNonRoot: true
#  # runAsUser: 1000
#
#
#
#ingress:
#  enabled: false
#  className: ""
#  annotations: {}
#    # kubernetes.io/ingress.class: nginx
#    # kubernetes.io/tls-acme: "true"
#  hosts:
#    - host: chart-example.local
#      paths:
#        - path: /
#          pathType: ImplementationSpecific
#  tls: []
#  #  - secretName: chart-example-tls
#  #    hosts:
#  #      - chart-example.local
#
#resources: {}
#  # We usually recommend not to specify default resources and to leave this as a conscious
#  # choice for the user. This also increases chances charts run on environments with little
#  # resources, such as Minikube. If you do want to specify resources, uncomment the following
#  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#  # limits:
#  #   cpu: 100m
#  #   memory: 128Mi
#  # requests:
#  #   cpu: 100m
#  #   memory: 128Mi
#
#autoscaling:
#  enabled: false
#  minReplicas: 1
#  maxReplicas: 100
#  targetCPUUtilizationPercentage: 80
#  # targetMemoryUtilizationPercentage: 80
#
#nodeSelector: {}
#
#tolerations: []
#
#affinity: {}
