management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: ${port:18083}
spring:
  main:
    allow-circular-references: true # Fix sprint-boot 2.6+
  application:
    name: ${name:service-consumer}
  cloud:
    nacos:
      discovery:
        fail-fast: true
        server-addr: ${nacos-server:127.0.0.1:8848}
      password: ${nacos-user:nacos}
      username: ${nacos-password:nacos}
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8080
      datasource:
        flow:
          nacos:
            server-addr: ${nacos-server:127.0.0.1:8848}
            username: ${nacos-user:nacos}
            password: ${nacos-password:nacos}
            dataId: service-consumer-flowrule
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
        degrade:
          nacos:
            server-addr: ${nacos-server:127.0.0.1:8848}
            username: ${nacos-user:nacos}
            password: ${nacos-password:nacos}
            dataId: service-consumer-degraderule
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: degrade

#        ds1:
#          file:
#            data-type: json
#            file: 'classpath: flowrule.json'
#            rule-type: flow
#        ds2:
#          file:
#            data-type: json
#            file: 'classpath: degraderule.json'
#            rule-type: degrade



# feign 超时设置 单位毫秒
feign:
  client:
    refresh-enabled: true
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
#  sentinel:
#    enabled: true
#  hystrix:
#    enabled: true

#ribbon:
#  eureka:
#    enabled: true
#  hystrix:
#    enabled: false
#  ConnectTimeout: 20000
#  ReadTimeout: 20000
#  OkToRetryOnAllOperations: true
#  MaxAutoRetriesNextServer: 3
#  MaxAutoRetries: 2
#hystrix:
#  threadpool:
##    service-res:
##      coreSize: 20
##      maxQueueSize: 200
##      queueSizeRejectionThreshold: 3
#    default:
#      coreSize: 10
#      maxQueueSize: 200
#      queueSizeRejectionThreshold: 2
#  command:
##    ResVenClient#getTree():
##      execution:
##        isolation:
##          thread:
##            timeoutInMilliseconds: 30000
#    default:
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#          strategy: THREAD
#          thread:
#            timeoutInMilliseconds: 1000
#            interruptOnTimeout: true
#            interruptOnFutureCancel: false
#          semaphore:
#            maxConcurrentRequests: 2
#      fallback:
#        enabled: true
#        isolation:
#          semaphore:
#            maxConcurrentRequests: 2
#      circuitBreaker:
#        enabled: true
#        forceOpen: true # 强制开启熔断
#        forceClosed: false # 强制忽略错误
#        requestVolumeThreshold: 4
#        errorThresholdPercentage: 50
#        sleepWindowInMilliseconds: 10000
#      metrics:
#        rollingStats:
#          timeInMilliseconds: 5000
#          numBuckets: 10
#        rollingPercentile:
#          enabled: true
#          timeInMilliseconds: 60000
#          numBuckets: 6
#          bucketSize: 100
#        healthSnapshot:
#          intervalInMilliseconds: 500